[book]
title = "RPNCalc User Guide"
authors = ["Michael Fross"]
description = "The RPNCalc User Guide"
language = "en"
src = "src"

[build]
build-dir = "RPNCalc-UserGuide"
create-missing = true
use-default-preprocessors = true

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
